import Head from 'next/head'
import { Inter } from '@next/font/google'
import { Header } from '../src/components/Header'
import { BannerSection } from '../src/components/sections/Banner'
import { WhatWeDoSection } from '../src/components/sections/WhatWeDo'
// import { BannerSection } from '../src/components/sections/banner/Banner'

export default function Home() {
  return (
    <>
      <Head>
        <title>Textuaria - Conteúdo Criativo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main style={{ height: '2000 px' }}>
        <BannerSection />
        <WhatWeDoSection />
      </main>
    </>
  )
}
